### ISSUE TITLE
About the python packge 'mc'

### ISSUE THREAD

**Issue by Coiner2121** [zhangyi-3/IDR#11]
Hi, while i was training your code on the windows, I cannot find the python package 'mc'(datasets/imagefolder.py Line 13). Is it means the 'python-memcached 1.59'? Expecting your explanation, and thanks a lot  :D

**Comment by zhangyi-3** [comment]
Thanks for your question! You can disable the Memcached (mc) directly in the [cfg](https://github.com/zhangyi-3/IDR/blob/b84b522be18fa2625a27c76f09765a1327fc58c4/configs/IDR.yaml#L64). Memcached doesn't affect the final performance but accelerates the data loading.
