### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by JerryLeolfl** [zhangyi-3/IDR#7]
Hi,
  Thanks for your excellent work. I got many download fails with the url offered. Could you please release another url which easy for downloading? Thanks a lot.

**Comment by zhangyi-3** [comment]
Hi, thanks for your interest in our dataset. The Baidu Netdisk link is provided. Feel free to contact me if you have other questions.

**Comment by JerryLeolfl** [comment]
Thanks a lot!
